### ISSUE TITLE
Constant PlayerInteractEvent messages on 1.18.

### ISSUE THREAD

**Issue by IoIxD** [rogermiranda1000/PortalGun#16]
On my end, at least, the following message fills the logs when I right click with an item in hand. 

```
[07:36:53 ERROR]: Could not pass event PlayerInteractEvent to PortalGun v2.2.3
java.lang.NullPointerException: Cannot invoke "org.bukkit.inventory.ItemStack.getType()" because "i" 
is null
        at com.rogermiranda1000.versioncontroller.items.ItemManager.sameItem(ItemManager.java:35) ~[P
ortalGun.jar:?]
        at com.rogermiranda1000.versioncontroller.items.ItemManager.hasItemInHand(ItemManager.java:57
) ~[PortalGun.jar:?]
        at com.rogermiranda1000.portalgun.eventos.onUse.onPlayerUse(onUse.java:28) ~[PortalGun.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor93.execute(Unkn
own Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.18.1-
R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.18.1
-R0.1-SNAPSHOT.jar:git-Paper-215]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.1
8.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:629) ~[paper-api-
1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEvent
Factory.java:544) ~[paper-1.18.1.jar:git-Paper-215]
        at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:542) ~
[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:1840) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:33) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.a(ServerboundUseItemOnPacket.java:9) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.18.1.jar:git-Paper-215]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1423) ~[paper-1.18.1.jar:git-Paper-215]
        at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:189) ~[paper-1.18.1.jar:git-Paper-215]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1400) ~[paper-1.18.1.jar:git-Paper-215]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1393) ~[paper-1.18.1.jar:git-Paper-215]
        at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:110) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1528) ~[paper-1.18.1.jar:git-Paper-215]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1273) ~[paper-1.18.1.jar:git-Paper-215]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-215]
        at java.lang.Thread.run(Thread.java:831) ~[?:?]
```

I am using Paper, version git-Paper-215, for 1.18.1, if that helps

**Comment by rogermiranda1000** [comment]
That looks like the plugin didn't read correctly the PortalGun item.
Have you tried to remove the configuration file and restarting the server? That way the plugin will generate a new correct configuration file.
